### ISSUE TITLE
Version of R

### ISSUE THREAD

**Issue by ermckinnon** [simaxwell/ggGSS#1]
Hi - I just want to check, what is the latest version of R that ggGSS will work with? A colleague is having difficulty getting it to work with 4.3.1 but it is working great for me with 4.2.1. Is there a known issue with 4.3.1?
thanks,
Ewen

**Comment by simaxwell** [comment]
Hi Ewen. No known issue that I am aware of. If you or your colleague send over a MRE I can take a look. Cheers -- Si.

**Comment by simaxwell** [comment]
no known issue.
